const root=document.getElementById('root'),tst=document.getElementById('toast');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=d=>new Date(d).toLocaleString([],{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const loc=d=>new Date(d-d.getTimezoneOffset()*6e4).toISOString().slice(0,16);
const NAV={ADMIN:[['dashboard','Dashboard'],['visitors','Visitors'],['visits','Visits'],['audit','Audit log']],HOST:[['dashboard','Dashboard'],['visitors','Visitors'],['visits','My visits']],SECURITY:[['security','Security console']]};
let me=null,page='',tt;
function toast(t,err){tst.textContent=t;tst.className=err?'err':'';tst.hidden=false;clearTimeout(tt);tt=setTimeout(()=>tst.hidden=true,3500)}
async function api(p,m='GET',b){const r=await fetch('/api/'+p,{method:m,headers:b?{'Content-Type':'application/json'}:{},body:b?JSON.stringify(b):undefined});const j=await r.json().catch(()=>({}));
 if(!r.ok){if(r.status===401&&me&&p!=='login'){me=null;boot()}throw new Error(j.error||'Something went wrong')}return j}
const pill=s=>`<span class="pill ${{APPROVED:'g',ALLOW:'g',SUCCESS:'g',PENDING:'a',STEP_UP:'a'}[s]||(['REJECTED','REVOKED','EXPIRED','DENY'].includes(s)?'r':'')}">${esc(s.replace('_','-'))}</span>`;
async function boot(){try{me=await api('me')}catch{me=null}me?go(NAV[me.role][0][0]):login()}
function login(){root.innerHTML=`<div class="login"><form class="box" data-f="login"><h1 style="margin:0">ZT Visitor</h1><p class="muted">Sign in to continue</p>
<div class="f"><label for="u"><b>Username</b></label><input id="u" name="username" autocomplete="username" required></div>
<div class="f"><label for="p"><b>Password</b></label><input id="p" name="password" type="password" autocomplete="current-password" required></div>
<button style="width:100%;margin-top:18px">Sign in</button></form></div>`}
function shell(body,title,help){root.innerHTML=`<aside class="side"><h1>ZT Visitor<small>Zero-Trust Access</small></h1>${NAV[me.role].map(([k,l])=>`<button class="${k===page?'on':''}" data-go="${k}">${l}</button>`).join('')}<button class="out" data-act="logout">Log out</button></aside>
<div class="main"><header class="top"><div><b>${title}</b><div class="muted">${help}</div></div><div><b>${esc(me.name)}</b> <span class="pill">${me.role}</span></div></header><div class="content">${body}</div></div>`}
const P={
async dashboard(){const s=await api('stats');return['Dashboard','Your visitor activity at a glance',`<div class="stats">${[['Registered visitors',s.visitors],['Visits',s.visits],['Waiting for approval',s.pending],['Active passes',s.active]].map(([l,n])=>`<div class="card"><span class="muted">${l}</span><strong>${n}</strong></div>`).join('')}</div>
<div class="card"><b>How access works</b><p class="muted">1. Register the visitor. 2. Create a visit request. 3. The host approves it and a QR pass is issued. 4. Security scans the pass; it is checked again for every zone. 5. The pass expires on its own, and every step is logged.</p></div>`]},
async visitors(){const v=await api('visitors');return['Visitors','Step 1: register each visitor with a synthetic ID reference',`<form class="card form" data-f="visitor"><div><label>Full name</label><input name="name" required maxlength="60"></div><div><label>Mobile (10 digits)</label><input name="phone" inputmode="numeric" required maxlength="10"></div><div><label>Email</label><input name="email" type="email" required></div><div><label>ID reference (optional)</label><input name="idRef" placeholder="Auto: SYN-ID-${1001+v.length}"></div><div style="align-self:end"><button>Register visitor</button></div></form>
<div class="card">${v.length?`<table><tr><th>Name</th><th>Mobile</th><th>Email</th><th>ID reference</th></tr>${v.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.phone)}</td><td>${esc(x.email)}</td><td>${pill(x.idRef)}</td></tr>`).join('')}</table>`:'<p class="muted">No visitors yet. Register the first one above.</p>'}</div>`]},
async visits(){const [v,vs,h]=await Promise.all([api('visits'),api('visitors'),me.role==='ADMIN'?api('hosts'):[]]);const n=new Date();
 return['Visits','Step 2: request access, then the host approves and a QR pass is issued',(vs.length?`<form class="card form" data-f="visit"><div><label>Visitor</label><select name="visitor">${vs.map(x=>`<option value="${x._id}">${esc(x.name)}</option>`).join('')}</select></div>${me.role==='ADMIN'?`<div><label>Host</label><select name="host">${h.map(x=>`<option value="${x._id}">${esc(x.name)}</option>`).join('')}</select></div>`:''}<div><label>Zone</label><select name="zone">${me.zones.map(z=>`<option>${esc(z)}</option>`).join('')}</select></div><div><label>Purpose</label><input name="purpose" required maxlength="80"></div><div><label>Valid from</label><input name="from" type="datetime-local" value="${loc(n)}" required></div><div><label>Valid until (max 12 hours)</label><input name="until" type="datetime-local" value="${loc(new Date(+n+72e5))}" required></div><div style="align-self:end"><button>Create request</button></div></form>`:'<div class="card muted">Register a visitor first.</div>')
 +`<div class="card">${v.length?`<table><tr><th>Visitor</th><th>Host</th><th>Zone and purpose</th><th>Valid</th><th>Status</th><th></th></tr>${v.map(x=>`<tr><td><b>${esc(x.visitor?.name)}</b></td><td>${esc(x.host?.name)}</td><td>${esc(x.zone)}<br><span class="muted">${esc(x.purpose)}</span></td><td>${fmt(x.from)}<br><span class="muted">to ${fmt(x.until)}</span></td><td>${pill(x.status)}</td><td>${x.status==='PENDING'?`<button data-act="approve" data-id="${x._id}">Approve</button> <button class="dng" data-act="reject" data-id="${x._id}">Reject</button>`:x.status==='APPROVED'?`<button class="dng" data-act="revoke" data-id="${x._id}">Revoke</button>`:''}</td></tr>`).join('')}</table>`:'<p class="muted">No visits yet.</p>'}</div>`]},
async security(){return['Security console','Scan the visitor\'s pass. Every entry is checked again, even for pass holders already inside',`<form class="card form" data-f="verify"><div><label>Pass token</label><input name="token" required autocomplete="off" maxlength="100"></div><div><label>Zone being entered</label><select name="zone">${me.zones.map(z=>`<option>${esc(z)}</option>`).join('')}</select></div><div><label>Visitor device</label><select name="device"><option value="KNOWN">Known and up to date</option><option value="UNKNOWN">Unknown device</option><option value="OUTDATED">Outdated or rooted device</option></select></div><div style="align-self:end"><button>Check access</button></div></form><div id="res"></div>`]},
async audit(){const a=await api('audit');return['Audit log','Each entry is linked to the one before it, so edits can be detected',`<div class="dec ${a.intact?'ALLOW':'DENY'}">${a.intact?`Log integrity verified: ${a.total} entries, none altered.`:'WARNING: the audit chain is broken. A record was changed or removed.'}</div><div class="card"><table><tr><th>Time</th><th>Who</th><th>Action</th><th>Item</th><th>Result</th><th>Details</th></tr>${a.logs.map(l=>`<tr><td>${fmt(l.createdAt)}</td><td>${esc(l.actor)}</td><td>${esc(l.action)}</td><td>${esc(l.resource)}</td><td>${pill(l.result)}</td><td class="muted">${esc(l.details)}</td></tr>`).join('')}</table></div>`]}};
async function go(p){page=p;try{const [t,h,b]=await P[p]();shell(b,t,h)}catch(e){toast(e.message,1)}}
function showPass(d){const m=document.createElement('div');m.className='mb';m.innerHTML=`<div class="md"><h3 style="margin-top:0">Visitor pass</h3><img src="${esc(d.qr)}" width="240" height="240" alt="QR pass"><p class="muted">Shown once. Only a hash is stored on the server.</p><div class="tok">${esc(d.token)}</div><button style="margin-top:14px" data-act="close">Done</button></div>`;document.body.appendChild(m)}
function result(r){document.getElementById('res').innerHTML=`<div class="dec ${r.decision}">${{ALLOW:'ACCESS ALLOWED',DENY:'ACCESS DENIED',STEP_UP:'EXTRA CHECK NEEDED'}[r.decision]}${r.visitor?' for '+esc(r.visitor):''} (risk ${r.score}/100)${r.reason?'<br>'+esc(r.reason):''}<ul class="ck">${r.checks.map(c=>`<li>${c.ok?'Pass':'Fail'}: ${esc(c.name)}</li>`).join('')}</ul>${r.decision==='STEP_UP'?'<button data-act="stepup" style="margin-top:8px">I checked the visitor\'s ID reference. Admit.</button>':''}</div>`}
document.addEventListener('submit',async e=>{const f=e.target.closest('[data-f]');if(!f)return;e.preventDefault();const d=Object.fromEntries(new FormData(f)),k=f.dataset.f;
 try{if(k==='login'){me=await api('login','POST',d);me=await api('me');go(NAV[me.role][0][0])}
 else if(k==='visitor'){await api('visitors','POST',d);toast('Visitor registered');go(page)}
 else if(k==='visit'){d.from=new Date(d.from).toISOString();d.until=new Date(d.until).toISOString();await api('visits','POST',d);toast('Visit request created');go(page)}
 else if(k==='verify'){window.last=d;result(await api('verify','POST',d))}}catch(x){toast(x.message,1)}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.act,id=b.dataset.id;if(b.dataset.go)return go(b.dataset.go);
 try{if(a==='logout'){await api('logout','POST',{});me=null;login()}
 else if(a==='close')b.closest('.mb').remove();
 else if(a==='approve'){showPass(await api(`visits/${id}/approve`,'POST',{}));go(page)}
 else if(a==='reject'||a==='revoke'){if(confirm((a==='reject'?'Reject':'Revoke')+' this visit?')){await api(`visits/${id}/${a}`,'POST',{});toast('Done');go(page)}}
 else if(a==='stepup')result(await api('verify','POST',{...window.last,stepUpDone:true}))}catch(x){toast(x.message,1)}});
boot();
